<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>,
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-resource.js"></script>
<script src="//ckeditor.com/apps/ckeditor/4.2/ckeditor.js"></script>
<script src="js/cms.js"></script>
<script src="js/services.js"></script>
<script src="js/notification.js"></script>

<div notifications="top right" class="cms-notifications"></div>
